### ISSUE TITLE
Issue/Question

### ISSUE THREAD

**Issue by EchocallingEarth** [flokol120/Spigot-Item-Chest-Sorter#1]
When using the plugin the chat is spammed by a Message if a block is in the sender chest that is not in a receiver chest.

Msg 

> "There are no receivers configured yet. Use the /ics add receiver command"

This message repeats for the number of items in a chest that have no receiver.
How to disable or fix this, please.

Once done I'll leave a review as other than this issue this plugin is perfect for my server's needs. But if I left a review now it would be less then favorable and I will not do that ever.

There appears to be no console log to provide but I can provide screenshots etc as needed if it helps.

Thanks in advance.

**Comment by flokol120** [comment]
This is definitely a bug! Than you for reporting it directly here on GitHub!
 
The Problem - in your case - was assumingly that you did not define any 'air chest' (which is completely fine and totally not an error on your side). This way the plugin thought you haven't got any receivers whilst you only didn't have any 'air receiver'.

I fixed the issue by moving the if-branch displaying the message and checking beforehand if you have any 'air receivers' or not.
Version 1.2.2 should be on the releases page in a minute. Please report back if this commit fixed your issue.

**Comment by EchocallingEarth** [comment]
Working perfectly fine and thank you
