### ISSUE TITLE
Request config option for per world item sorting

### ISSUE THREAD

**Issue by EchocallingEarth** [flokol120/Spigot-Item-Chest-Sorter#10]
Requesting a change in the config to allow admin/owner to decide permission on allowing or denying world to world item sorting. Currently not possible and if attempted throws a huge in console error.

If this is not an option then let me know so I can request a bug report be filed that would remove the console error and fix it with a chat message to the player saying something along the lines of "sorry per world item sorting is not possible"

Log etc available upon request.

**Comment by flokol120** [comment]
@EchocallingEarth Sorry for not responding quicker. Strangely I am not receiving any notifications from GitHub :(

This is a bug which I - admittedly - know existed. This however is not an easy fix. But I will look into it as soon as I have some free time.

**Comment by flokol120** [comment]
The cross world sorting feature is now implemented. Permissions will be implemented in a future update.
