### ISSUE TITLE
There should be an option to delete all receiver and sender chest claims to make a new claim

### ISSUE THREAD

**Issue by AwooCrewSevilla** [flokol120/Spigot-Item-Chest-Sorter#11]
while the tool has been extremely useful, it is a very tedious process to have to hit T and click every time you want to delete a chest, and if you do it too many times you get kicked from a server for spamming, if there was a mass remove all claims on all the chests to be able to start the system over it would make expanding the send/receive chests a lot easier when you mess something up.

**Comment by flokol120** [comment]
@AwooCrewSevilla Thanks for the interest in my plugin! If you delete a sender all its receivers are going to be deleted to. Is this what you are trying to achieve or did I misunderstand you?

**Comment by flokol120** [comment]
closed due to inactivity.
