### ISSUE TITLE
Unable to connect multiple sender chests to one reciever chest

### ISSUE THREAD

**Issue by revetz** [flokol120/Spigot-Item-Chest-Sorter#12]
Not really sure what the problem is, just isn't working

**Comment by flokol120** [comment]
This is not supported and will not be due to early design choices. You could achieve what you want to do by first defining a sender which sends items to another sender which than sends those items to your desired receivers.

**Comment by flokol120** [comment]
Whoops, the feature I am refering to is not yer published. It will be as soon as I have time to do further work on #8.
