### ISSUE TITLE
sorting items outside of their item 'type'

### ISSUE THREAD

**Issue by imteekzo** [flokol120/Spigot-Item-Chest-Sorter#13]
is/would it be possible to sort items outside of their type into the same container using sets?

for example, to sort all logs and planks into one chest, or to sort all armor types and slots (iron pants, diamond boots, leather chest etc) into one chest?

i have tried defining sets using all 3 methods outlined in the config.yml but have no success with getting items outside of their item type into the same chest

here's a screenshot from my config file showing all 3 methods i used - 
![testmethods](https://user-images.githubusercontent.com/67780866/86521696-5fd90100-be11-11ea-8502-146da2c68ac4.png)

**Comment by flokol120** [comment]
The feature is not really tied on an items "type". Please provide your config.yml as text, I do not have time and joy copying those sets from your screenshot for further testing :stuck_out_tongue_winking_eye:

**Comment by flokol120** [comment]
Also, what is your setup in-game?

**Comment by imteekzo** [comment]
[config.yml.txt](https://github.com/flokol120/Spigot-Item-Chest-Sorter/files/4876509/config.yml.txt)

here's the config in text format. as mentioned before i tried 3 different methods and none of the three worked, they're all labelled as "structure group" #1, 2 and 3.

my setup in-game is very simple right now, it's just one sender and one receiver chest. receiver chest has an item frame, and i have tried various items in the frame corresponding with each item in the set.

with the currently active log and plank set, i can get all logs to push to the receiver box, but planks will not push to that box if a log is in the item frame. if i swap the item in the frame to a plank, all planks will send to that receiver, but then logs will not

**Comment by flokol120** [comment]
Thank you for providing those information! That is very strange. I will take a deeper look into it.

**Comment by flokol120** [comment]
All sets are working as expected for me. Which version are you using? Did you reload the server when you changed the sets within the config.yml? 
A small mistake in your regex sets (but I doubt this is related to your issue as you commented those out): When using regex you need to put single quotes before every item:
`- ['.*_chestplate, .*_helmet, .*_leggings, .*_boots']` --> `- ['.*_chestplate', '.*_helmet', '.*_leggings', '.*_boots']`

**Comment by imteekzo** [comment]
i totally understand what i did wrong now. when i first installed the mod i was using an auto installed version via multicraft and it was not pulling the config from the file at all. i just uninstalled the auto installed version, rebuilt the jar myself in intellij and uploaded it manually. with the config file next to chests.json in /Item-Chest-Sorter/ it's now working seamlessly

thank you very much for clarifying the proper structure of the sets, i really appreciate the help and apologize for not realizing this sooner

**Comment by flokol120** [comment]
Not a problem. I am glad I could help!
