### ISSUE TITLE
Shulkerbox into shulkerbox into ...

### ISSUE THREAD

**Issue by FirstLadyAnna** [flokol120/Spigot-Item-Chest-Sorter#14]
Es ist bei Minecraft nicht umsonst unmöglich, Shulkerkisten in Shulkerkisten zu füllen! Mit ICS geht das aber! Spieler können eine Shulkerkiste als Empfänger einrichten und können die gefüllten Shulkerkisten in den Sender packen. Damit werden die gefüllten Shulkerkisten in eine Shulkerkiste gepackt und diese kann man dann abbauen und theoretisch wieder in eine Senderkiste packen. Irgendwann rechnet sich der Server dann tot. Bitte verhindere, dass man Shulkerkisten als Empfänger definieren kann, sonst ist das Plugin unbrauchbar.

**Comment by flokol120** [comment]
@FirstLadyAnna Thanks for your input. This makes total sense. The next time you file an issue on GitHub, make sure to formulate it in english for others to understand. It is really annoying to find something you cannot understand. Short translation:
It is possible to define shulker boxes as senders and receivers. Shulker boxes, however are meant to be picked up. This leads to the server looking for a box which could be just gone. 

This "issue" however also applies to other containers: If you break a chest within a sender/receiver system the server cannot find it. But I do understand that shulker boxes are meant to be broken. I will add a new param to the config file which controls whether shulker boxes are allowed or not.

This should be an easy fix.

**Comment by FirstLadyAnna** [comment]
Sorry for my bad english. Iam glad that you will fix it. Server chrashes are not nice

**Comment by flokol120** [comment]
@FirstLadyAnna No need to apologize, my english is far from perfect as well. It is already fixed. If you want it to be disabled, you just have to replace the .jar file in your plugins folder with the newest 1.7.1 version.

**Comment by FirstLadyAnna** [comment]
Many Thanks for qick resonse and quick fix!!! Its terrific!
 Unfortunately, the players can still dismantle the already registered receiver box and place a shulker box instead. Since only the location of the box is registered, it is unfortunately still possible to pack Shulker boxes in Shulker boxes.

**Comment by flokol120** [comment]
@FirstLadyAnna Oh, Touché. I will try to detect that. But preventing that in the first place would be more tricky. But I will look into that...

**Comment by flokol120** [comment]
@FirstLadyAnna If a chest is replaced with a shulker box, the plugin refuses to send items to it. Please report back if it fixed now.

**Comment by FirstLadyAnna** [comment]
I'm so happy! Now it's perfect! Nice job, and especially so fast! Thank you very much!

**Comment by flokol120** [comment]
@FirstLadyAnna Glad you like it! You were lucky you got me on a free sunday. Usually I am not that fast if I got other work to do :stuck_out_tongue:

**Comment by FirstLadyAnna** [comment]
All's well that ends well.
