### ISSUE TITLE
ICS with PlotSquared

### ISSUE THREAD

**Issue by Psyconcept** [flokol120/Spigot-Item-Chest-Sorter#17]
Hello I have the plugin on my CityBuild server. It works as promised, but I don't think it's compatible with PlotSquared. Because users on stranger plots can also create Sender boxes, and on their plots receivers. Is there any solution for a user to use it ONLY on his plot and on no strangers?

**Comment by flokol120** [comment]
@Psyconcept Hi, thanks for the interest in my plugin. I am afraid I do not have time to implement that feature because I would have to read their API docs. But if you happen to have experience + time you could try to implement it yourself as this plugin is open-source.
