### ISSUE TITLE
[Suggestion] Configurable Chat

### ISSUE THREAD

**Issue by IgnorantMountaineer** [flokol120/Spigot-Item-Chest-Sorter#18]
Not a big deal, but flokol if you're looking to continue improving this, one idea may be to allow for a configurable chat as, at the moment, it's sometimes a bit much for users.

**Comment by flokol120** [comment]
@IgnorantMountaineer what do you exactly mean by "configurable chat"? A global flag to disable chat messages?

**Comment by IgnorantMountaineer** [comment]
Sure, I would say at a basic level, the first thing would be to disable or enabled "sorting messages". I.e. "You sorted X amount of items" message could be turned off. 

`val message = "${ChatColor.GREEN}sorted ${ChatColor.YELLOW}${amount} ${ChatColor.GREEN}${ChatColor.AQUA}${getItemName(content)} ${ChatColor.GREEN}to your chest"
        if(player != null) {
            player.sendMessage(message)`

is the code block I'm referring too I believe. That's the first priority in my mind. The second thing would be to turn off warning messages, like the message when a chest is about to be full, or when it will be sorted into the air chest.

**Comment by flokol120** [comment]
@IgnorantMountaineer implemented in 1.8.1
Maybe you can report back if this works as intended.

**Comment by IgnorantMountaineer** [comment]
> @IgnorantMountaineer implemented in 1.8.1
> Maybe you can report back if this works as intended.

Sure, will check tomorrow! Thanks for the continued support on this great project.

**Comment by flokol120** [comment]
closed due to inactivity
