### ISSUE TITLE
NPE on Inventory Close Event

### ISSUE THREAD

**Issue by EscolarProgramming** [flokol120/Spigot-Item-Chest-Sorter#19]
Hello,
We get spammed with NPE's from your plugin. We're running on git-Paper-186 (MC: 1.16.2) with Item Chest Sorter v1.7.3.

Here's the stacktrace: https://hastebin.com/ebosidaziv

It would be nice if you could have a look :)

**Comment by flokol120** [comment]
Hey, this looks very similar to #16 As stated before, paper is not and will not be supported. If you can reproduce this issue with a spigot server, I am willing to take a look into it.

**Comment by EscolarProgramming** [comment]
Ah sorry, I hadn't looked into the closed ones. I will try to reproduce it, and also look into the code to figure out the problem with paper.

**Comment by flokol120** [comment]
Nice, thanks for your contribution!

**Comment by flokol120** [comment]
closed due to inactivity. Feel free to reopen.
