### ISSUE TITLE
Flat-DB has 3MB size

### ISSUE THREAD

**Issue by Leahcimkrob** [flokol120/Spigot-Item-Chest-Sorter#21]
Can you add MySQL-Support?

**Comment by flokol120** [comment]
@Leahcimkrob I dont really see the use in adding relational database support. The json file is read after the plugin is loaded and kept in-memory to be super fast. But feel free to implement it yourself, if you are able to.

**Comment by Leahcimkrob** [comment]
The Flat-File has 3 MB, if a user add another Chest to his System, the server will lagging.

**Comment by flokol120** [comment]
@Leahcimkrob never experienced any lag on my server as it is being held in-memory. But I guess if you are low on memory this could be an issue :thinking: Unfortunately though I do not have enough free time to implement this feature. Maybe in a few months. As this would be quite a big change.

**Comment by Leahcimkrob** [comment]
![image](https://user-images.githubusercontent.com/70509359/104846761-75f56d00-58dc-11eb-9b95-81c02916629b.png)

The timing for ICS increases steadily as soon as a user uses the ICS

**Comment by Leahcimkrob** [comment]
So now the flat file is 4 MB. If there are 10 players on the server and one of them creates a new receiver chest, the TPS goes down, if there are 2 players in a row, the server crashes. Without ICs, the server is stable even with 40 players.

**Comment by flokol120** [comment]
Thanks for keeping me updated, but I am still very short on free time :(

**Comment by flokol120** [comment]
@Leahcimkrob I have just released 1.8.0 which introduces a 'performance mode'. Please update the plugin, enable the said 'performance mode' and report back.

**Comment by Leahcimkrob** [comment]
Sorry, but we use an other Sorter-Plugin.
