### ISSUE TITLE
Feature Request - limit chest creation via permission

### ISSUE THREAD

**Issue by VimaMT** [flokol120/Spigot-Item-Chest-Sorter#25]
Could you consider, maybe, setting up a permission node that we can set which specifies how many receiver chests a player can create, based upon either the player or the permission group which the player is in?

For instance, if the player or the group had a permission, ics.max.10, then they could only create 10 receiving chests.

**Comment by flokol120** [comment]
@VimaMT this should now be working with 1.10.0: https://github.com/flokol120/Spigot-Item-Chest-Sorter/releases/tag/1.10.0

Please report back if this is the behavior you expected.

**Comment by flokol120** [comment]
@VimaMT one last ping, before closing 😛

**Comment by flokol120** [comment]
Closed due to inactivity
