### ISSUE TITLE
Can you make download link from spingot not a external link?

### ISSUE THREAD

**Issue by MknGui** [flokol120/Spigot-Item-Chest-Sorter#33]
I have used your plugin in another servers and I wanna use in a server from Aternos, but it don't acept external links.
if you can't it's all right, forgive me for the inconvenience sz
Sorry, for my english, i didn't write for a long time, i'm brazilian.

**Comment by flokol120** [comment]
Hi there, thanks for the interest in my plugin.
I am not sure how I can help you with that 🤔Sounds like an issue with your server provider to me. But if there is something I can do, please tell me what 😁

**Comment by MknGui** [comment]
Ty, I'll change the provider
 I love your plugin 🥰

**Comment by flokol120** [comment]
@MknGui alright, but maybe I could have helped you :thinking: Were can you download plugins from using Aternos?

**Comment by MknGui** [comment]
only bukkit and spingot, i can't up by myself, i guess it's for security, but aternos is free to play i should not ask for much.

i can't add your plugin because the download is from here "external link", not by the spingot site 

sorry my English again, appreciate the patience

**Comment by flokol120** [comment]
@MknGui Okay, I understand now. Idea of providing the jar files here was to also centralize the issues on github. But if it would help some people (you), I am happy to upload the jar to spigot aswell. That's not big of a deal.

**Comment by flokol120** [comment]
Arg, I am sorry but I cannot upload the .jar file to spigot as it exceeds the max. file size allowed by spigot :( Sorry about that.
