### ISSUE TITLE
Problems with hopper

### ISSUE THREAD

**Issue by f1nnie2210** [flokol120/Spigot-Item-Chest-Sorter#41]
I have enabled sendFromHopperOrSender and sendFromHopperOrSenderNoEmptySlot but its still didnt work, no items have been move :((

**Comment by flokol120** [comment]
@f1nnie2210 cannot not be reproduced on my end. Which Minecraft version are you using? Are you using Spigot or Paper (or something else)? Which Version of the plugin are you using? What is your exact setup (which item is in the item frame of the receiver, screenshot would also be very helpful)? Please provide your config.yml

**Comment by flokol120** [comment]
closed due to inactivity
