### ISSUE TITLE
Any plans for 1.20 ?

### ISSUE THREAD

**Issue by BarbokOL** [flokol120/Spigot-Item-Chest-Sorter#47]
Sorry to be that guy, but Im just curious if you will update this plugin to 1.20 anytime soon or if I should look for an alternative for now.
It does run on 1.20 but it's pretty buggy, chests not sorting correctly, making new item groups in the config often not working, and chests stopping to recognize both sender and receiver.

**Comment by flokol120** [comment]
Nothing to be sorry about, thanks for bringing this to my attention. As I am currently not playing minecraft, I had no idea 1.20 came out :). But I'll take a look into it, but can't make any promises when it'll be ready.

**Comment by flokol120** [comment]
@BarbokOL I just did some quick testing and everything is working fine for me in 1.20. Please provide me with more information in order for me to investigate this further:

Are you using Spigot or Paper?
Are animations enabled?
What distances are between your sender/receivers? (don't need an exact block count, just estimate it)

And also please provide your config.yml.

**Comment by BarbokOL** [comment]
#Hey, thanks for the quick response and checking even tho you aren't playing at the moment.
The Server is running on paper
animations are off
They are all in a big underground storage, the whole space is around 50x50 blocks
[config.txt](https://github.com/flokol120/Spigot-Item-Chest-Sorter/files/11929142/config.txt)

The biggest issue I've encountered so far is honestly that sometimes like said above it just thinks the sender or receiver doesn't exist, telling me to add them with the command.
I just can't seem to replicate the issue as it's pretty random.

**Comment by flokol120** [comment]
Alright. I just found out I've a small error in the template config.yml in the flower set. But that shouldn't™️ be the issue:

```yaml
...
  - [dandelion, poppy, blue_orchid, allium, azure_bluet, red_tulip, orange_tulip, white_tulip, pink_tulip,
  oxeye_daisy, cornflower, lily_of_the_valley, wither_rose, sunflower, lilac, rose_bush, peony]
...
```
should be (or just in one line)
```yaml
...
  - [
      dandelion,
      poppy,
      blue_orchid,
      allium,
      azure_bluet,
      red_tulip,
      orange_tulip,
      white_tulip,
      pink_tulip,
      oxeye_daisy,
      cornflower,
      lily_of_the_valley,
      wither_rose,
      sunflower,
      lilac,
      rose_bush,
      peony,
    ]
...
```

Besides fixing this in your config.yml please set `allowBreakOfChest: true` to `false` this will prevent anything from breaking chests defined as sender or receivers. Maybe that got your setup confused, because some chest is missing.

If this is however as random as you state, I am sorry I cannot do much as long as I cannot reproduce it :(

**Comment by BarbokOL** [comment]
Okay, first, thanks for correcting the config.
I will try what you suggested and will play a day or two to see if there is any more weird stuff going on, will report back if there is!

**Comment by BarbokOL** [comment]
Okay, it seems fixed as long as I completely remove all the chests and readd them to the system again, a bit roundabout but so far that works.

**Comment by flokol120** [comment]
> Okay, it seems fixed as long as I completely remove all the chests and readd them to the system again, a bit roundabout but so far that works.

Alright, good to hear. If you however are able to reproduce this behavior in the future, feel free to reach out to me again!

**Comment by BarbokOL** [comment]
Okay it happened again, 
"Currently there is no sender chest selected. At first select a sender chest using /sorther select sender and right clicking a sender chest."
All I did this time was restart my game and relog and try to add a new chest to the system.

**Comment by flokol120** [comment]
Ahhh, now I know what is happening 😁 you first need to select your sender chest with the sender hoe. This is the same hoe you use to create a new sender. Or just use `/ics select sender`. After that right click your sender chest and it will be selected. Afterwards you can add receivers to this sender again.

This way it is possible to have multiple sender/receiver systems, by selecting the correct sender prior to adding receivers.

So this is not a bug, it is actually a feature!

I admit though that this is not documented well enough. I should really write a documentation™️

**Comment by BarbokOL** [comment]
Yeah, after some more testing last night I kind of figured that might've been the case, cause after I set the sender again on the same chest, (had to remove the chest completely to add a new receiver) it also removed every one of the receiver chests and I was able to select all the chests as receiver again. it still feels a bit unintended but maybe im just not fully getting it yet.

**Comment by flokol120** [comment]
You dont have to delete the sender, just select it by right clicking the sender chest.

Sender chest with id 'id' is now selected.

If you want to remove this chest instead, please click on the next message in the chat (!This also implies the deletion of the receiver chests!)

Those are the chat messages which are displayed after selecting a sender chest. It also informs you that you can delete the sender chest including all receivers if you want to.

**Comment by BarbokOL** [comment]
Okay I can confirm now that my main confusion does come from the tools you are given,
for example, when the plugin tells you to use a remove command, giving you a tool to remove chests from a system but at the same time if you miss click a chest that is not in a system that remove tool adds it to the system instead of just ignoring it or giving an error, it would be nice to have separate tools so that does not happen.

Maybe even give completely different tools to not mix it up, like for removing a sender you get an axe, for adding a hoe etc.

Overall, the feature I would probably want the most rn is the fact that if you are giving yourself a remover hoe tool that should only actually remove a chest and not add it to the system if it already is added. 
I can imagine it not mattering that much for a smaller storage but if you use the system on a big storage, it gets really confusing quite quickly and usually you end up adding a chest by accident and then all the overflow goes in there when you didn't mean to etc.

**Comment by flokol120** [comment]
I understand. Feel free to open a feature request. But no promises on when I'll be able to implement this, because this wont be as trivial as it sounds.
