### ISSUE TITLE
Sets are not working

### ISSUE THREAD

**Issue by ReySniperio** [flokol120/Spigot-Item-Chest-Sorter#50]
- [spruce_.*]
  - [oak_.*]
  - [dark_oak_.*]
  - [birch_.*]
  - [acacia_.*]
  - [mangrove_.*]
  - [cherry_.*]
  - [jungle_.*]
  - [warped_.*]
  - [hyphae_.*]

I made the sets as shown above. The spruce one is working but the other dont.
Am I doing something wrong?

**Comment by flokol120** [comment]
@ReySniperio Please follow the Bug-Template. It'll make debugging your issue way easier.

**Comment by flokol120** [comment]
Closed due to inactivity
