### ISSUE TITLE
[REQUEST] Include Barrels as a sender/receiver

### ISSUE THREAD

**Issue by baesik** [flokol120/Spigot-Item-Chest-Sorter#51]
**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**
Add the ability to make barrels senders and receivers just like chests. Additionally, it should work with dynamic item slots. Specifically, Purpur's ability to force barrels to have 6 rows (just like chests).

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by baesik** [comment]
Nevermind, this feature was added 3 years ago and was too lazy to search before requesting because I didn't see barrels mentioned anywhere in the description.

**Comment by flokol120** [comment]
Strange...
https://github.com/flokol120/Spigot-Item-Chest-Sorter/blob/cfd00d533cf08061a41a82ed02835fb1394fad25/src/main/kotlin/com/flodoerr/item_chest_sorter/Listener.kt#L48C63-L48C63
Should already include Barrels 🤔 But I can take a look into it

**Comment by flokol120** [comment]
> Nevermind, this feature was added 3 years ago and was too lazy to search before requesting because I didn't see barrels mentioned anywhere in the description.

Oh, alright :D 👍
