### ISSUE TITLE
[REQUEST] Add max receiver distance

### ISSUE THREAD

**Issue by flokol120** [flokol120/Spigot-Item-Chest-Sorter#53]
**Describe the solution you'd like**
Add a new config value to set the maximum distance for a receiver/sender set. Setting the distance to 0 will disable the distance check. 0 will be the default value for backwards compatibility.

Feature idea from daoshi (SpigotMC.org).

**Comment by daoshii** [comment]
Thank you so much, Looking forward to the progress on this!
