### ISSUE TITLE
Set misconfiguration

### ISSUE THREAD

**Issue by tinyalpaca** [flokol120/Spigot-Item-Chest-Sorter#55]
Hello, I installed your plugins into my Minecraft paper server. However, the command can't be used. When I type in /ics add sender, it prompts out the message "Usage: /ics [add|select|remove] [sender|receiver]".

**Comment by tinyalpaca** [comment]
Hi @flokol120, I tried again with a fresh file download. It is indeed working. 

Then I try to edit the config.yml to add more sets. I attach what i edited as below. 
Also, do i need to repack or such things? 
Normally I just open the jar file with winrar and just open the file with notepad, edit and save. With that said, I edited the config.yml with that method. I only touch the "set:" part. Can you check it for me? 
Also, I tried the example 1.1 by just removing the "#" as you mentioned but it also not working. 

Maybe can you run this config.yml and see if it is successful.

I'm playing at a Paper 1.20.1 server


Minecraft Version: 1.20.1
Server Flavor:Paper
Plugin Version 1.14.4
![image](https://github.com/flokol120/Spigot-Item-Chest-Sorter/assets/121000182/f4eeebef-b812-46d3-b295-4f4e47675b5d)
`# Version 1.14.4

# If enabled = false the plugin will not do anything
enabled: true

# Performance mode
# if enabled not every new chest is directly saved to the disk. This can be useful for big servers and servers with HDD
# drives. !But his may lead to data loss if the server crashes!
performance: false
# only used if performance mode is set to true. Autosaves after set interval (in minutes)
autoSaveInterval: 5

# animation configuration
animation:
  # If true items are being animated. If false no animation will be drawn
  # IMPORTANT: Animations are not compatible with 1.19.2 and above!
  enabled: false
  # If true all items are being animated. If false only one item will be animated (only used if enabled = true)
  animateAll: false

# move items when they are moved into a sender chest by a hopper or another sender chest.
# This feature could be not safe to use! Enable with caution.
# keep in mind that setting this to true can imply a small loss of performance.
#
# To safe some resources it can be only triggered if the chest is full. Triggers the sorting as soon as no empty slot
# is in the chest
sendFromHopperOrSender: false
sendFromHopperOrSenderNoEmptySlot: false

# allows shulker boxes to be used as sender and/or receivers.
# Breaking shulker boxes without deleting them from a sender/receiver system will result in errors.
allowShulkerBoxes: false

# allows the use of Regular Expressions in sets
# example: '.*_log' to match all things that end with "_log"
enableSetsRegex: true

# defines whether user can break chests which are defined as sender and/or receivers
# if set to true users CAN break containers registered by this plugin, if set to false users CANNOT break them.
# keep in mind that setting this to false can imply a small loss of performance.
allowBreakOfChest: true

# the max distance (spherical) distance between a sender and a receiver. This value is both validated on a receiver
# creation and item send events. If the value is set to '0' no limitations are in place.
maxReceiverDistance: 0

# ability to enable/disable certain chat messages
chatMessages:
  # sends a message to a player or the console after sorting, containing which and how many items are sorted
  sorted: true
  # sends a message if shulker boxes are disabled and a player tries tu use them
  disabledShulkerBoxes: true
  # sends a message if a player tries to break a sender/receiver chest
  breakingChests: true
  # sends a message if a chest is defined as a receiver but does not have an item frame attached to it
  noItemFrame: true
  # sends a message to a player if items will be sorted into an 'air chest'
  sortinToAirChest: true
  # sends a message to a player or the console if no receivers are configured for a sender
  noReceivers: true
  # sends a message to a player or the console if a chest is full after the sorting is completed
  fullChest: true
  # sends a message to a player if a receiver chest is out of the 'maxReceiverDistance'.
  # Not displayed if 'maxReceiverDistance' is 0.
  outOfRangeReceiver: true

# define sets if you want similar items to be moved to just one chest
# look at the examples if you want to add a new set.
# define a new array by beginning the line with - []
# separate the items by commas.
# you have to use the so called 'namespaced IDs'. You can find those in the minecraft wiki for almost all items.
# example namespaced IDs: https://minecraft.gamepedia.com/Flower#Data_values
sets:
# example 1.1: Move all wool colors to the same chest (using explicit all ids)
# remove the '#' in the next two lines if you want to move all different colored wool blocks into one chest
  - [white_wool, orange_wool, magenta_wool, light_blue_wool, yellow_wool, lime_wool, pink_wool, gray_wool,
  light_gray_wool, cyan_wool, purple_wool, blue_wool, brown_wool, green_wool, red_wool, black_wool]

# example 1.2: Move all wool colors to the same chest (using regex)
# remove the '#' in the next line if you want to move all different colored wool blocks into one chest
#  - ['.*_wool']

# example 2: Move all flowers to the same chest
  remove the '#' in the next two lines if you want to move all different flowers into one chest
  - [dandelion, poppy, blue_orchid, allium, azure_bluet, red_tulip, orange_tulip, white_tulip, pink_tulip, oxeye_daisy, cornflower, lily_of_the_valley, wither_rose, sunflower, lilac, rose_bush, peony]

# All wood and planks
  - [oak_planks, birch_planks, spruce_planks, jungle_planks, acacia_planks, dark_oak_planks, crimson_planks]
  
# All wood 
  - [oak_wood, birch_wood, spruce_wood, jungle_wood, acacia_wood, dark_oak_wood, crimson_wood, stripped_birch_wood, stripped_spruce_wood, stripped_jungle_wood, stripped_acacia_wood, stripped_dark_oak_wood]
 
# All sapling and small plants
  - [oak_sapling, birch_sapling, spruce_sapling, jungle_sapling, acacia_sapling, bamboo_sapling, dark_oak_sapling, grass, fern, dead_bush, seagrass, sea_pickle]
  
# All seeds
  - [wheat_seeds, melon_seeds, pumpkin_seeds, beetroot_seeds]
  
# All functional block
  -[anvil, crafting_table, furnace, enchanting_table, hopper, dropper]
  
# All wood derivable
  -['.*_slab','.*_sign', '.*_door', '.*_fence', '.*_stairs', '.*_button', '.*_trapdoor', '.*_fence_gate', '.*_pressure_plate']`

**Comment by flokol120** [comment]
@tinyalpaca No, you do not want to edit the plugin.yml within the jar file. You should not edit anything within jar files unless you know exactly what you are doing.

The correct config file to edit is `Item-Chest-Sorter/plugin.yml` within the plugins folder. In the future, please provide any text documents within the backtick notation of (using three ` to start a code-block and again three to end it). As far as I can tell from your screenshot, you are missing a line comment in line 84. That means you have to add a `#` at the beginning of this line.

If this does not fix the error, please provide your *complete* `config.yml` within a code block as outlined above. Hope that helps!

**Comment by flokol120** [comment]
Feel free to reopen the issue if something is still unclear.
