### ISSUE TITLE
Question about how the plugin works.

### ISSUE THREAD

**Issue by KIMTID** [flokol120/Spigot-Item-Chest-Sorter#56]
Hello, I got a message: Found item(s) which are not specified. Sorting into air chest, if there is enough space…
Tell me what an air chest is and how it can be created?

**Comment by flokol120** [comment]
@KIMTID: An “air chest” is a receiver chest with an item frame which holds **no item/block**. This way, you can define _fallbacks_ if no other item frame holds a specific item. 

I hope that clarifies it. If not, feel free to report back. Otherwise, you can close the issue.

**Comment by flokol120** [comment]
Closed due to inactivity
