### ISSUE TITLE
[BUG] 1.20.6 Not Working

### ISSUE THREAD

**Issue by BrandonS8** [flokol120/Spigot-Item-Chest-Sorter#57]
**Describe the bug**
Right clicking with the hoe it gives seems to do nothing, as if it never detects a click. No errors or anything. 

**To Reproduce**
Steps to reproduce the behavior/What triggers the error:
Use command to get hoe that sets as sender or receiver and right click a chest

**Expected behavior**
It would set a chest as sender or receiver

**Config**
Using the default config

**Screenshots**

**Version Information**
- Minecraft Version: 1.20.6
- Server Flavor: Paper
- Plugin Version 1.14.4

**Additional context**
I believe a lot of api changes happened on 1.20.5 and 1.20.6, seems like maybe the checks for the right item in hand in the listener are not working anymore or something.

**Comment by flokol120** [comment]
@BrandonS8 Thanks for reporting the issue. I plan to take a look into it within the next two weeks, as I am pretty busy right now.

**Comment by Virologicbody** [comment]
Same issue for me.
The plugin carries on working with any chests that are already set up before updating to 1.20.6, it's just the chest selection/hoe that doesn't work.
I have a few chests that I needed to relocate, but I found a janky way around it until we hopefully get a working update.

Still a great plugin though!

**Comment by flokol120** [comment]
@BrandonS8, @Virologicbody fixed in version 1.14.5
